export const CONFIG = {
  tickMs: 50,
  patchMs: 50,
  inputSendMs: 33,
  reconnectSeconds: 20,
  maxPlayers: 4,
  realSecondsPerGameMinute: 3,
  roundEndClock: 240,
  watcherSpawnClock: 30,
  lightsHalfClock: 180,
  hornClock: 230,
  player: {
    radius: 0.35,
    walkSpeed: 3,
    runSpeed: 5,
    staminaMax: 5,
    staminaRegen: 1,
    hp: 2,
    ambientRadius: 1.5,
    slots: 3,
    weightSlowPerKg: 0.01,
    weightSlowMax: 0.3,
    interactRange: 1.2,
    departHoldSeconds: 3,
  },
  flashlight: { angle: Math.PI / 3, range: 8, batteryMax: 180 },
  noise: { walk: 1.5, run: 8, drop: 6 },
  items: {
    countAt4: 25,
    minCount: 10,
    valueMin: 10,
    valueMax: 80,
    weightMin: 2,
    weightMax: 15,
    totalFactor: 1.8,
  },
  difficulty: {
    1: { target: 150, stalkers: 1, stalkerSpeedMul: 0.85 },
    2: { target: 250, stalkers: 1, stalkerSpeedMul: 1 },
    3: { target: 350, stalkers: 2, stalkerSpeedMul: 1 },
    4: { target: 450, stalkers: 2, stalkerSpeedMul: 1 },
  },
  stalker: {
    patrolSpeed: 2.5,
    investigateSpeed: 3.5,
    chaseSpeed: 4.5,
    sightRange: 6,
    loseSeconds: 5,
    searchSeconds: 5,
    retreatSeconds: 3,
    lateSpeedMul: 1.1,
    radius: 0.4,
  },
  watcher: { speed: 5.5, radius: 0.4, waitSeconds: 1 },
  ghost: { speed: 6, flickerRadius: 3, flickerSeconds: 1.5, flickerCooldown: 10 },
  comms: {
    pingSeconds: 3,
    pingCooldown: 3,
    chatCooldown: 1,
    quickChats: ['여기로', '도와줘!', '폐품 있음', '도망쳐!', '비춰줘!', '트럭으로'],
  },
  net: { maxMessagesPerSecond: 60, maxDt: 0.1, nicknameMax: 10, interpolationMs: 100 },
  fx: { dangerDistance: 5 },
} as const;
