export const CONFIG = {
  tickMs: 50,
  patchMs: 50,
  inputSendMs: 33,
  reconnectSeconds: 20,
  maxPlayers: 4,
  realSecondsPerGameMinute: 3,
  roundEndClock: 240,
  watcherSpawnClock: 30,
  lightsHalfClock: 180,
  hornClock: 230,
  player: {
    radius: 0.35,
    walkSpeed: 3,
    runSpeed: 5,
    staminaMax: 5,
    staminaDrain: 1,
    staminaRegen: 1,
    staminaRecoverToRun: 1,
    hp: 2,
    ambientRadius: 1.5,
    slots: 3,
    weightSlowPerKg: 0.01,
    weightSlowMax: 0.3,
    interactRange: 1.2,
    departHoldSeconds: 3,
  },
  movement: { maxStep: 0.25 },
  flashlight: { angle: Math.PI / 3, range: 8, batteryMax: 180, drainPerSecond: 1 },
  noise: { walk: 1.5, run: 8, drop: 6 },
  items: {
    countAt4: 25,
    minCount: 10,
    valueMin: 10,
    valueMax: 80,
    weightMin: 2,
    weightMax: 15,
    totalFactor: 1.8,
  },
  difficulty: {
    1: { target: 150, stalkers: 1, stalkerSpeedMul: 0.85 },
    2: { target: 250, stalkers: 1, stalkerSpeedMul: 1 },
    3: { target: 350, stalkers: 2, stalkerSpeedMul: 1 },
    4: { target: 450, stalkers: 2, stalkerSpeedMul: 1 },
  },
  stalker: {
    patrolSpeed: 2.5,
    investigateSpeed: 3.5,
    chaseSpeed: 4.5,
    sightRange: 6,
    loseSeconds: 5,
    searchSeconds: 5,
    retreatSeconds: 3,
    lateSpeedMul: 1.1,
    radius: 0.4,
  },
  watcher: { speed: 5.5, radius: 0.4, waitSeconds: 1 },
  ghost: { speed: 6, flickerRadius: 3, flickerSeconds: 1.5, flickerCooldown: 10 },
  comms: {
    pingSeconds: 3,
    pingCooldown: 3,
    chatCooldown: 1,
    quickChats: ['여기로', '도와줘!', '폐품 있음', '도망쳐!', '비춰줘!', '트럭으로'],
  },
  net: { maxMessagesPerSecond: 60, maxInputsPerBatch: 10, maxDt: 0.1, nicknameMax: 10, roomCodeLength: 6, interpolationMs: 100 },
  /** 화면 기준 해상도(px)와 1타일의 기준 px(스펙 4.1). */
  view: { width: 960, height: 540, tilePx: 32 },
  fx: {
    dangerDistance: 5,
    /** 어둠 레이어 불투명도: 생존자 / 유령(스펙 4.3). */
    darknessAlpha: 0.95,
    ghostDarknessAlpha: 0.6,
    /** 깜빡이는 조명의 점멸 빈도: Math.floor(t * flickerBlinkHz) % 2일 때 켜짐. */
    flickerBlinkHz: 12,
    /** 트럭 구역(출입구) 주변의 넓은 빛 반경(타일). */
    truckLightRadius: 6,
    /** 빛 가장자리 흐림: 반경 대비 이 비율부터 어두워진다. */
    lightSoftEdge: 0.6,
    /** 화면 밖 광원도 반경 + 여유(타일)가 화면에 닿으면 계산한다. */
    lightCullMargin: 2,
    shakeSeconds: 0.3,
    shakeTiles: 0.18,
    /** 유령끼리 보일 때의 불투명도. */
    ghostAlpha: 0.45,
    chatLogSize: 5,
    /** HUD 안내(경적, 사망 등) 표시 시간(초). */
    noticeSeconds: 4,
  },
  pathfinding: { stairsCost: 1 },
} as const;
